hw6_2_1: hw6_2_1.c avl.c rb.c bst.c
	gcc hw6_2_1.c avl.c rb.c bst.c -o hw6_2_1

hw6_2_2: hw6_2_2.c avl.c rb.c bst.c
	gcc hw6_2_2.c avl.c rb.c bst.c -o hw6_2_2

hw6_2_3: hw6_2_3.c avl.c rb.c bst.c
	gcc hw6_2_3.c avl.c rb.c bst.c -o hw6_2_3
	
clean:
	rm -r hw6_2_1 hw6_2_2 hw6_2_3
